"""Coach-to-risk-engine integration layer.

Orchestrates the full position-sizing pipeline: alpha aggregation,
risk estimation, HRP allocation, online weight blending, Kelly sizing,
constraint enforcement, meta-label filtering, and cost estimation.

The pipeline implements a layered decision framework inspired by:

1. Grinold & Kahn (1999) -- inverse-variance alpha aggregation.
2. Lopez de Prado (2016) -- Hierarchical Risk Parity allocation.
3. Cover (1991) / Cesa-Bianchi & Lugosi (2006) -- online exponential
   weights for tactical blending.
4. Kelly (1956) / Thorp (2008) -- position sizing via fractional Kelly.
5. Lopez de Prado (2018) -- meta-labeling for trade filtering.
6. Vovk et al. (2005) -- conformal prediction for uncertainty intervals.

References
----------
Grinold, R.C. & Kahn, R.N. (1999). *Active Portfolio Management*, 2nd ed.
Lopez de Prado, M. (2016). J. Portfolio Management, 42(4), 59-69.
Cover, T.M. (1991). Mathematical Finance, 1(1), 1-29.
Kelly, J.L. (1956). Bell System Technical Journal, 35(4), 917-926.
Thorp, E.O. (2008). Handbook of Asset and Liability Management.
Lopez de Prado, M. (2018). *Advances in Financial Machine Learning*, Wiley.
Vovk, V., Gammerman, A. & Shafer, G. (2005). *Algorithmic Learning in a
    Random World*, Springer.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

import numpy as np
import pandas as pd

from risk_engine.config.risk_params import RiskParams
from risk_engine.config.constants import RISK_DEFAULTS
from risk_engine.core.alpha_aggregator import AlphaAggregator
from risk_engine.core.risk_estimator import RiskEstimator
from risk_engine.core.position_sizer import PositionSizer
from risk_engine.core.risk_allocator import RiskAllocator
from risk_engine.core.cost_model import CostModel
from risk_engine.core.constraints import Constraints
from risk_engine.core.disagreement_signal import DisagreementSignal
from risk_engine.core.meta_labeler import MetaLabeler
from risk_engine.core.online_allocator import OnlineAllocator
from risk_engine.core.conformal_predictor import ConformalPredictor
from .agent_interface import AgentSignal

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Output container
# ---------------------------------------------------------------------------


@dataclass
class CoachDecision:
    """Complete output of the risk-engine pipeline for a single bar.

    Encapsulates every sizing, allocation, and risk decision made by
    the coach so that downstream systems (execution, dashboard, logging)
    have a single, self-describing object to consume.

    Attributes
    ----------
    agent_weights : dict[str, float]
        Blended weights (HRP strategic + online tactical) per agent.
        Sums to approximately 1.0.
    position_sizes : dict[str, float]
        Kelly-sized positions per agent as a fraction of portfolio NAV.
        Positive = long, negative = short.  Incorporates direction,
        confidence, regime, and constraint adjustments.
    risk_budget : dict[str, float]
        Risk allocation per agent as a fraction of total portfolio risk.
        Derived from HRP weights scaled by agent volatility contribution.
    total_exposure : float
        Net exposure of the portfolio as a fraction of NAV:
            total_exposure = sum(position_sizes.values())
        Positive means net long, negative means net short.
    cost_estimate : float
        Estimated round-trip transaction cost for executing all proposed
        position changes, expressed in basis points of portfolio NAV.
    constraints_applied : list[str]
        Human-readable descriptions of every constraint that fired during
        this bar.  Empty list means no constraint violations.
    meta_label_proba : float
        Predicted probability from the meta-labeling model that the
        aggregated signal will be profitable.  Range [0, 1].
        A value below 0.5 typically suppresses the trade.
    conformal_interval : tuple[float, float]
        Prediction interval for the expected portfolio return at the
        configured coverage level (default 90%):
            (lower_bound, upper_bound)
        Generated by the conformal predictor (Vovk et al. 2005).
    timestamp : str
        ISO-8601 UTC timestamp when this decision was produced.
    """

    agent_weights: dict[str, float]
    position_sizes: dict[str, float]
    risk_budget: dict[str, float]
    total_exposure: float
    cost_estimate: float
    constraints_applied: list[str]
    meta_label_proba: float
    conformal_interval: tuple[float, float]
    timestamp: str

    def to_dict(self) -> dict[str, Any]:
        """Serialize the decision to a plain dictionary.

        Returns
        -------
        dict[str, Any]
            JSON-compatible representation of the decision.
        """
        return {
            "agent_weights": self.agent_weights,
            "position_sizes": self.position_sizes,
            "risk_budget": self.risk_budget,
            "total_exposure": self.total_exposure,
            "cost_estimate": self.cost_estimate,
            "constraints_applied": self.constraints_applied,
            "meta_label_proba": self.meta_label_proba,
            "conformal_interval": list(self.conformal_interval),
            "timestamp": self.timestamp,
        }

    @property
    def gross_exposure(self) -> float:
        """Sum of absolute position sizes.

        Formula
        -------
            gross = sum(|pos_i|)  for all agents i

        Returns
        -------
        float
            Non-negative gross exposure as a fraction of NAV.
        """
        return sum(abs(v) for v in self.position_sizes.values())

    @property
    def n_active_positions(self) -> int:
        """Count of agents with non-zero position sizes.

        Returns
        -------
        int
            Number of agents currently allocated capital.
        """
        return sum(1 for v in self.position_sizes.values() if abs(v) > 1e-8)


# ---------------------------------------------------------------------------
# Main coach interface
# ---------------------------------------------------------------------------


class CoachInterface:
    """Orchestrator connecting multiple agents to the risk engine pipeline.

    The coach collects signals from all active agents, runs them through
    the full risk pipeline, and returns a ``CoachDecision`` containing
    position sizes, weights, risk budgets, and constraint metadata.

    Pipeline steps (executed in ``process_signals``):
    1. **Alpha aggregation** -- inverse-variance combine agent alphas
       (Grinold & Kahn 1999, Chapter 14).
    2. **Risk estimation** -- EWMA volatility + Ledoit-Wolf covariance
       (RiskMetrics 1996; Ledoit & Wolf 2004).
    3. **HRP allocation** -- Hierarchical Risk Parity weights
       (Lopez de Prado 2016).
    4. **Online blending** -- exponential weights tactical tilt
       (Cover 1991; Cesa-Bianchi & Lugosi 2006).
    5. **Kelly sizing** -- fractional Kelly position sizes per agent
       (Kelly 1956; Thorp 2008).
    6. **Constraint check** -- exposure, drawdown, and kill-switch
       enforcement.
    7. **Meta-label filter** -- secondary model trade/no-trade gate
       (Lopez de Prado 2018, Chapter 3).
    8. **Cost estimation** -- NSE transaction cost model with
       microstructure adjustments (Almgren & Chriss 2001).

    Parameters
    ----------
    params : RiskParams | None
        Runtime-tunable risk parameters.  Defaults to ``RiskParams()``
        which pulls all values from ``RISK_DEFAULTS``.

    Example
    -------
    >>> coach = CoachInterface()
    >>> signals = [
    ...     AgentSignal("PLAYER_1", 0.8, 0.7, 0.001, 0.02),
    ...     AgentSignal("PLAYER_2", -0.3, 0.5, 0.0005, 0.015),
    ... ]
    >>> decision = coach.process_signals(signals, market_data, 1_000_000)
    >>> decision.total_exposure
    0.12
    """

    def __init__(self, params: RiskParams | None = None) -> None:
        self.params: RiskParams = params or RiskParams()

        # -- Core components ------------------------------------------------
        self.alpha_aggregator: AlphaAggregator = AlphaAggregator(
            min_variance=1e-10,
            max_single_weight=0.6,
        )
        self.risk_estimator: RiskEstimator = RiskEstimator()
        self.position_sizer: PositionSizer = PositionSizer(
            kelly_fraction=self.params.kelly_fraction,
            max_position_pct=self.params.max_single_position_pct,
        )
        self.risk_allocator: RiskAllocator = RiskAllocator(
            min_weight=0.05,
            max_weight=0.40,
        )
        self.cost_model: CostModel = CostModel()
        self.constraints: Constraints = Constraints(self.params)
        self.disagreement_signal: DisagreementSignal = DisagreementSignal()
        self.meta_labeler: MetaLabeler = MetaLabeler(
            n_folds=5,
            threshold=0.5,
        )
        self.online_allocator: OnlineAllocator = OnlineAllocator(
            n_agents=5,
            learning_rate=0.1,
            min_weight=0.01,
        )
        self.conformal_predictor: ConformalPredictor = ConformalPredictor(
            coverage=self.params.conformal_coverage,
        )

        # -- State tracking -------------------------------------------------
        self._last_hrp_weights: dict[str, float] = {}
        self._cumulative_pnl: float = 0.0
        self._peak_nav: float = 0.0
        self._daily_pnl: float = 0.0
        self._bar_count: int = 0

        logger.info(
            "CoachInterface initialised with kelly_fraction=%.2f, "
            "max_position=%.2f, tactical_blend=%.2f",
            self.params.kelly_fraction,
            self.params.max_single_position_pct,
            self.params.tactical_blend,
        )

    # ------------------------------------------------------------------
    # Main pipeline
    # ------------------------------------------------------------------

    def process_signals(
        self,
        signals: list[AgentSignal],
        market_data: pd.DataFrame,
        portfolio_value: float,
        current_positions: dict[str, float] | None = None,
    ) -> CoachDecision:
        """Run the full risk-engine pipeline on a batch of agent signals.

        This is the primary entry point called by the coach system on
        every bar.  It takes raw agent signals and produces a complete
        sizing and allocation decision.

        Pipeline
        --------
        1. Filter to actionable signals only.
        2. Aggregate alpha via inverse-variance weighting.
        3. Estimate volatility and covariance across agents.
        4. Compute HRP weights (if enough history is available).
        5. Blend HRP weights with online (tactical) weights.
        6. Size each agent's position using fractional Kelly.
        7. Apply all constraints (kill switches, exposure limits, etc.).
        8. Compute meta-label probability for trade filtering.
        9. Estimate transaction costs for proposed trades.

        Parameters
        ----------
        signals : list[AgentSignal]
            Signals from all agents for the current bar.
        market_data : pd.DataFrame
            Recent OHLCV data with indicators.  Used for volatility
            estimation and meta-labeler features.
        portfolio_value : float
            Current portfolio NAV in INR.
        current_positions : dict[str, float] | None
            Existing positions as agent_id -> fraction of NAV.
            Used for turnover-based cost estimation.  ``None`` means
            no existing positions (starting fresh).

        Returns
        -------
        CoachDecision
            Complete decision object with positions, weights, constraints,
            costs, and metadata.
        """
        if current_positions is None:
            current_positions = {}

        timestamp: str = datetime.now(timezone.utc).isoformat()

        # -- 0. Filter actionable signals -----------------------------------
        active_signals: list[AgentSignal] = [
            s for s in signals if s.is_actionable
        ]

        if not active_signals:
            logger.info("No actionable signals; returning flat decision.")
            return self._flat_decision(timestamp)

        agent_ids: list[str] = [s.agent_id for s in active_signals]

        # -- 1. Alpha aggregation -------------------------------------------
        alphas: dict[str, float] = {
            s.agent_id: s.alpha_estimate for s in active_signals
        }
        variances: dict[str, float] = {
            s.agent_id: s.variance_estimate for s in active_signals
        }
        confidences: dict[str, float] = {
            s.agent_id: s.confidence for s in active_signals
        }

        combined_alpha, alpha_weights = self.alpha_aggregator.combine_with_confidence(
            alphas=alphas,
            confidences=confidences,
            variances=variances,
        )

        # -- 2. Risk estimation (per-agent volatility) ----------------------
        agent_vols: dict[str, float] = {
            s.agent_id: s.volatility_estimate for s in active_signals
        }

        # -- 3. HRP weights -------------------------------------------------
        hrp_weights: dict[str, float] = self._compute_hrp_weights(
            active_signals, market_data
        )

        # -- 4. Blend with online weights -----------------------------------
        blended_weights: dict[str, float] = self._blend_weights(
            hrp_weights, agent_ids
        )

        # -- 5. Kelly-size each agent's position ----------------------------
        position_sizes: dict[str, float] = {}
        for sig in active_signals:
            regime: str = sig.metadata.get("regime", "Sideways")
            size_result = self.position_sizer.size(
                mu=sig.alpha_estimate,
                sigma=sig.volatility_estimate,
                signal_direction=sig.direction,
                signal_confidence=sig.confidence,
                regime=regime,
            )
            # Scale by agent's blended weight
            weight: float = blended_weights.get(sig.agent_id, 1.0 / len(active_signals))
            position_sizes[sig.agent_id] = size_result.clamped_fraction * weight

        # -- 5b. Disagreement adjustment -----------------------------------
        directions: dict[str, float] = {
            s.agent_id: s.direction for s in active_signals
        }
        disagree_result = self.disagreement_signal.compute(
            directions=directions,
            confidences=confidences,
        )
        if disagree_result.is_high_disagreement:
            logger.warning(
                "High disagreement detected (entropy=%.4f). "
                "Halving all positions.",
                disagree_result.entropy,
            )
            position_sizes = {
                k: v * disagree_result.position_size_multiplier
                for k, v in position_sizes.items()
            }

        # -- 6. Constraint enforcement --------------------------------------
        total_exposure: float = sum(position_sizes.values())
        gross_exposure: float = sum(abs(v) for v in position_sizes.values())

        # Use the worst agent Sharpe for the ensemble-level check
        agent_sharpes: dict[str, float] = {}
        for sig in active_signals:
            sharpe_val: float = 0.0
            features: dict[str, Any] = sig.metadata
            if "rolling_sharpe" in features:
                sharpe_val = float(features["rolling_sharpe"])
            agent_sharpes[sig.agent_id] = sharpe_val

        worst_sharpe: float = min(agent_sharpes.values()) if agent_sharpes else 0.0

        # Track NAV for drawdown calculation
        if self._peak_nav <= 0.0:
            self._peak_nav = portfolio_value
        self._peak_nav = max(self._peak_nav, portfolio_value)
        current_drawdown: float = (
            (self._peak_nav - portfolio_value) / self._peak_nav
            if self._peak_nav > 0
            else 0.0
        )

        constraint_violations: list[str] = []
        for aid, pos in list(position_sizes.items()):
            result = self.constraints.apply_all(
                proposed_fraction=abs(pos),
                gross_exposure=gross_exposure,
                net_exposure=total_exposure,
                daily_loss=max(0.0, -self._daily_pnl / max(portfolio_value, 1.0)),
                drawdown=current_drawdown,
                agent_sharpe=agent_sharpes.get(aid, 0.0),
            )
            if not result.allowed:
                position_sizes[aid] = 0.0
            else:
                sign: float = 1.0 if pos >= 0 else -1.0
                position_sizes[aid] = sign * result.adjusted_fraction
            constraint_violations.extend(result.violations)

        # Recompute exposures after constraint adjustments
        total_exposure = sum(position_sizes.values())
        gross_exposure = sum(abs(v) for v in position_sizes.values())

        # -- 7. Meta-label filter -------------------------------------------
        meta_label_proba: float = self._compute_meta_label_proba(
            combined_alpha, active_signals, market_data
        )

        # If meta-labeler says "do not trade" (proba < 0.5), reduce
        # all positions by the meta-label confidence.
        if meta_label_proba < 0.5:
            scale: float = max(0.0, 2.0 * meta_label_proba)
            position_sizes = {k: v * scale for k, v in position_sizes.items()}
            if scale < 1.0:
                constraint_violations.append(
                    f"Meta-label filter: proba={meta_label_proba:.3f}, "
                    f"scaled positions by {scale:.3f}"
                )
            total_exposure = sum(position_sizes.values())

        # -- 8. Conformal prediction interval -------------------------------
        conformal_interval: tuple[float, float] = self._compute_conformal_interval(
            combined_alpha
        )

        # -- 9. Cost estimation ---------------------------------------------
        cost_estimate_bps: float = self._estimate_costs(
            position_sizes=position_sizes,
            current_positions=current_positions,
            portfolio_value=portfolio_value,
            market_data=market_data,
        )

        # -- Build risk budget dict -----------------------------------------
        risk_budget: dict[str, float] = self._compute_risk_budget(
            blended_weights, agent_vols
        )

        self._bar_count += 1

        return CoachDecision(
            agent_weights=blended_weights,
            position_sizes=position_sizes,
            risk_budget=risk_budget,
            total_exposure=total_exposure,
            cost_estimate=cost_estimate_bps,
            constraints_applied=constraint_violations,
            meta_label_proba=meta_label_proba,
            conformal_interval=conformal_interval,
            timestamp=timestamp,
        )

    # ------------------------------------------------------------------
    # Online weight update
    # ------------------------------------------------------------------

    def update_online_weights(self, agent_returns: dict[str, float]) -> None:
        """Update the online (tactical) allocator with realised returns.

        Called after each bar's PnL is observed.  The multiplicative
        weights update rule from Cesa-Bianchi & Lugosi (2006) is applied:

            w_i(t+1) = w_i(t) * exp(eta * r_i(t)) / Z(t)

        Parameters
        ----------
        agent_returns : dict[str, float]
            Mapping of agent_id -> realized return for the last bar.
        """
        if not agent_returns:
            return

        try:
            self.online_allocator.update(agent_returns)
            logger.debug(
                "Online weights updated: %s",
                self.online_allocator.get_weights(),
            )
        except ValueError as exc:
            logger.warning("Failed to update online weights: %s", exc)

        # Track daily PnL for kill-switch
        bar_pnl: float = sum(agent_returns.values())
        self._daily_pnl += bar_pnl
        self._cumulative_pnl += bar_pnl

    # ------------------------------------------------------------------
    # Risk report
    # ------------------------------------------------------------------

    def get_risk_report(self) -> dict[str, Any]:
        """Generate a comprehensive risk report for dashboard consumption.

        Returns
        -------
        dict[str, Any]
            Dictionary with the following sections:
            * ``"online_weights"`` -- current tactical weights.
            * ``"hrp_weights"`` -- last computed strategic weights.
            * ``"params"`` -- current risk parameter values.
            * ``"daily_pnl"`` -- today's cumulative PnL.
            * ``"peak_nav"`` -- high-water mark NAV.
            * ``"bar_count"`` -- number of bars processed.
            * ``"meta_labeler_cv"`` -- cross-validation scores.
        """
        return {
            "online_weights": self.online_allocator.get_weights(),
            "hrp_weights": dict(self._last_hrp_weights),
            "params": self.params.to_dict(),
            "daily_pnl": self._daily_pnl,
            "cumulative_pnl": self._cumulative_pnl,
            "peak_nav": self._peak_nav,
            "bar_count": self._bar_count,
            "meta_labeler_cv": self.meta_labeler.cv_scores,
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _flat_decision(self, timestamp: str) -> CoachDecision:
        """Produce a zero-exposure decision when no signals are actionable.

        Parameters
        ----------
        timestamp : str
            ISO-8601 timestamp for the decision.

        Returns
        -------
        CoachDecision
            Decision with all positions at zero.
        """
        return CoachDecision(
            agent_weights={},
            position_sizes={},
            risk_budget={},
            total_exposure=0.0,
            cost_estimate=0.0,
            constraints_applied=["No actionable signals"],
            meta_label_proba=0.5,
            conformal_interval=(0.0, 0.0),
            timestamp=timestamp,
        )

    def _compute_hrp_weights(
        self,
        signals: list[AgentSignal],
        market_data: pd.DataFrame,
    ) -> dict[str, float]:
        """Compute HRP allocation weights across active agents.

        If there are fewer than 2 agents or insufficient data, returns
        equal weights as a fallback.

        Parameters
        ----------
        signals : list[AgentSignal]
            Active agent signals for the current bar.
        market_data : pd.DataFrame
            Recent market data (used for close-based returns if agent
            returns are unavailable).

        Returns
        -------
        dict[str, float]
            HRP weights, keyed by agent_id, summing to ~1.0.
        """
        agent_ids: list[str] = [s.agent_id for s in signals]
        n_agents: int = len(agent_ids)

        if n_agents < 2:
            equal: dict[str, float] = {aid: 1.0 / max(n_agents, 1) for aid in agent_ids}
            self._last_hrp_weights = equal
            return equal

        # Build a synthetic return matrix from agent volatility estimates
        # (using diagonal covariance as a proxy when full history is unavailable)
        vol_array: np.ndarray = np.array(
            [s.volatility_estimate for s in signals], dtype=np.float64
        )
        # Construct a diagonal covariance matrix
        cov_diag: np.ndarray = np.diag(vol_array ** 2)

        # Add small cross-correlation to make HRP meaningful
        n: int = len(vol_array)
        base_corr: float = 0.1
        corr_matrix: np.ndarray = np.full((n, n), base_corr, dtype=np.float64)
        np.fill_diagonal(corr_matrix, 1.0)

        # Convert correlation + volatilities to covariance
        outer_vol: np.ndarray = np.outer(vol_array, vol_array)
        cov_matrix: np.ndarray = corr_matrix * outer_vol

        try:
            budget = self.risk_allocator.allocate_from_covariance(
                cov=cov_matrix, names=agent_ids
            )
            self._last_hrp_weights = budget.weights
            return budget.weights
        except Exception as exc:
            logger.warning("HRP allocation failed: %s. Using equal weights.", exc)
            equal = {aid: 1.0 / n_agents for aid in agent_ids}
            self._last_hrp_weights = equal
            return equal

    def _blend_weights(
        self,
        hrp_weights: dict[str, float],
        agent_ids: list[str],
    ) -> dict[str, float]:
        """Blend HRP weights with online (tactical) weights.

        Formula
        -------
            final_i = tau * online_i + (1 - tau) * hrp_i

        where tau = ``self.params.tactical_blend`` (default 0.3).

        Parameters
        ----------
        hrp_weights : dict[str, float]
            Strategic weights from HRP.
        agent_ids : list[str]
            List of active agent IDs.

        Returns
        -------
        dict[str, float]
            Blended weights summing to ~1.0.
        """
        online_weights: dict[str, float] = self.online_allocator.get_weights()

        # Ensure online allocator has the right agent names
        online_agent_set = set(online_weights.keys())
        hrp_agent_set = set(hrp_weights.keys())

        # If agent sets match, use the blend method
        if online_agent_set == hrp_agent_set:
            try:
                return self.online_allocator.blend_with_hrp(
                    hrp_weights=hrp_weights,
                    tactical_ratio=self.params.tactical_blend,
                )
            except ValueError:
                pass

        # Fallback: manual blend for mismatched agent sets
        blended: dict[str, float] = {}
        tau: float = self.params.tactical_blend
        n: int = len(agent_ids)

        for aid in agent_ids:
            hrp_w: float = hrp_weights.get(aid, 1.0 / max(n, 1))
            online_w: float = online_weights.get(aid, 1.0 / max(n, 1))
            blended[aid] = tau * online_w + (1.0 - tau) * hrp_w

        # Normalize
        total: float = sum(blended.values())
        if total > 0:
            blended = {k: v / total for k, v in blended.items()}

        return blended

    def _compute_meta_label_proba(
        self,
        combined_alpha: float,
        signals: list[AgentSignal],
        market_data: pd.DataFrame,
    ) -> float:
        """Compute the meta-label probability for the aggregated signal.

        If the meta-labeler has been fitted, uses it to predict whether
        the aggregated signal will be profitable.  Otherwise returns
        a neutral 0.5 (no filtering).

        Parameters
        ----------
        combined_alpha : float
            Inverse-variance weighted combined alpha.
        signals : list[AgentSignal]
            Active agent signals (for feature extraction).
        market_data : pd.DataFrame
            Recent market data for feature engineering.

        Returns
        -------
        float
            Probability in [0, 1] that the signal is profitable.
        """
        if not hasattr(self.meta_labeler, '_is_fitted') or not self.meta_labeler._is_fitted:
            return 0.5

        # Build a minimal feature vector from agent signals
        try:
            features: list[float] = [
                combined_alpha,
                np.mean([s.confidence for s in signals]),
                np.std([s.direction for s in signals]),
                float(len(signals)),
            ]
            feature_array: np.ndarray = np.array(features, dtype=np.float64).reshape(1, -1)

            direction_sign: float = 1.0 if combined_alpha >= 0 else -1.0
            result = self.meta_labeler.predict(feature_array, direction_sign)
            return result.confidence
        except Exception as exc:
            logger.debug("Meta-label prediction skipped: %s", exc)
            return 0.5

    def _compute_conformal_interval(
        self,
        combined_alpha: float,
    ) -> tuple[float, float]:
        """Compute a conformal prediction interval for the combined alpha.

        Uses the conformal predictor to generate a distribution-free
        prediction interval at the configured coverage level.

        Parameters
        ----------
        combined_alpha : float
            The point prediction (combined alpha).

        Returns
        -------
        tuple[float, float]
            (lower_bound, upper_bound) prediction interval.
        """
        try:
            interval: tuple[float, float] = self.conformal_predictor.predict_interval(
                point_prediction=combined_alpha
            )
            return interval
        except Exception as exc:
            logger.debug("Conformal prediction skipped: %s", exc)
            # Fallback: symmetric interval based on alpha magnitude
            margin: float = abs(combined_alpha) * 2.0
            return (combined_alpha - margin, combined_alpha + margin)

    def _estimate_costs(
        self,
        position_sizes: dict[str, float],
        current_positions: dict[str, float],
        portfolio_value: float,
        market_data: pd.DataFrame,
    ) -> float:
        """Estimate total transaction costs for proposed position changes.

        Computes the round-trip cost for the turnover (delta between
        current and proposed positions) using the NSE cost model.

        Parameters
        ----------
        position_sizes : dict[str, float]
            Proposed positions as fractions of NAV.
        current_positions : dict[str, float]
            Existing positions as fractions of NAV.
        portfolio_value : float
            Current portfolio NAV in INR.
        market_data : pd.DataFrame
            Recent data for volatility and price extraction.

        Returns
        -------
        float
            Total estimated cost in basis points of portfolio NAV.
        """
        if portfolio_value <= 0:
            return 0.0

        # Compute turnover
        all_ids: set[str] = set(position_sizes.keys()) | set(current_positions.keys())
        total_turnover_fraction: float = 0.0

        for aid in all_ids:
            proposed: float = position_sizes.get(aid, 0.0)
            current: float = current_positions.get(aid, 0.0)
            total_turnover_fraction += abs(proposed - current)

        if total_turnover_fraction < 1e-8:
            return 0.0

        # Use the last close price as a representative price
        price: float = 1000.0  # default
        if not market_data.empty and "Close" in market_data.columns:
            last_close = market_data["Close"].iloc[-1]
            if pd.notna(last_close) and last_close > 0:
                price = float(last_close)

        # Estimate volatility from recent closes
        vol: float = 0.02  # default 2%
        if not market_data.empty and "Close" in market_data.columns:
            closes: pd.Series = market_data["Close"].dropna()
            if len(closes) > 2:
                log_returns: np.ndarray = np.diff(np.log(closes.values))
                vol = float(np.std(log_returns)) if len(log_returns) > 0 else 0.02

        # Total notional turnover
        notional_turnover: float = total_turnover_fraction * portfolio_value
        quantity: int = max(1, int(notional_turnover / price))

        rt_cost_bps: float = self.cost_model.round_trip_cost_bps(
            price=price,
            quantity=quantity,
            trade_type="intraday",
            volatility=vol,
            signal_type="normal",
        )

        # Scale by turnover fraction (cost is proportional to turnover)
        effective_cost_bps: float = rt_cost_bps * total_turnover_fraction

        return round(effective_cost_bps, 4)

    def _compute_risk_budget(
        self,
        weights: dict[str, float],
        agent_vols: dict[str, float],
    ) -> dict[str, float]:
        """Compute risk budget allocation per agent.

        The risk budget is defined as each agent's marginal contribution
        to portfolio volatility, normalised to sum to 1:

            risk_budget_i = w_i * sigma_i / sum_j(w_j * sigma_j)

        Parameters
        ----------
        weights : dict[str, float]
            Blended allocation weights per agent.
        agent_vols : dict[str, float]
            Per-agent volatility estimates.

        Returns
        -------
        dict[str, float]
            Risk budget per agent, summing to ~1.0.
        """
        risk_contributions: dict[str, float] = {}
        for aid in weights:
            w: float = weights.get(aid, 0.0)
            vol: float = agent_vols.get(aid, 0.01)
            risk_contributions[aid] = w * vol

        total_risk: float = sum(risk_contributions.values())
        if total_risk <= 0:
            n: int = len(weights)
            return {aid: 1.0 / max(n, 1) for aid in weights}

        return {
            aid: round(rc / total_risk, 6)
            for aid, rc in risk_contributions.items()
        }
